import { tenantContext } from "@/lib/tenant-context";
import { grade8BAdditionalStudentSeeds } from "@/features/students/services/mock-students";
import type { Guardian, GuardianStudentRelationship } from "@/features/guardians/types/guardian";

export const mockGuardians: Guardian[] = [
  {
    id: "guardian-meera-kulkarni",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    firstName: "Meera",
    lastName: "Kulkarni",
    displayName: "Meera Kulkarni",
    occupation: "Architect",
    employer: "Studio Eleven",
    email: "meera.kulkarni@example.test",
    primaryPhone: "+91 90000 01001",
    alternatePhone: "+91 90000 01002",
    address: "Wakad",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    postalCode: "411057",
    preferredLanguage: "English",
    status: "active",
    verificationStatus: "verified",
    createdAt: "2026-04-02T09:30:00+05:30",
    updatedAt: "2026-08-08T11:20:00+05:30",
  },
  {
    id: "guardian-sameer-kulkarni",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    firstName: "Sameer",
    lastName: "Kulkarni",
    displayName: "Sameer Kulkarni",
    occupation: "Consultant",
    email: "sameer.kulkarni@example.test",
    primaryPhone: "+91 90000 01003",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    status: "active",
    verificationStatus: "pending",
    createdAt: "2026-04-02T09:40:00+05:30",
    updatedAt: "2026-08-08T11:25:00+05:30",
  },
  {
    id: "guardian-nikhil-deshmukh",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    firstName: "Nikhil",
    lastName: "Deshmukh",
    displayName: "Nikhil Deshmukh",
    occupation: "Business Owner",
    email: "nikhil.deshmukh@example.test",
    primaryPhone: "+91 90000 02001",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    status: "active",
    verificationStatus: "verified",
    createdAt: "2026-04-04T10:10:00+05:30",
    updatedAt: "2026-08-10T14:05:00+05:30",
  },
  {
    id: "guardian-rohit-nair",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    firstName: "Rohit",
    lastName: "Nair",
    displayName: "Rohit Nair",
    occupation: "Legal Guardian",
    primaryPhone: "+91 90000 03001",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    status: "active",
    verificationStatus: "unverified",
    createdAt: "2026-04-08T12:45:00+05:30",
    updatedAt: "2026-08-11T09:50:00+05:30",
  },
  {
    id: "guardian-anita-sharma",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    firstName: "Anita",
    lastName: "Sharma",
    displayName: "Anita Sharma",
    primaryPhone: "+91 90000 04001",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    status: "active",
    verificationStatus: "verified",
    createdAt: "2026-04-10T11:15:00+05:30",
    updatedAt: "2026-08-09T16:30:00+05:30",
  },
  {
    id: "guardian-archived-contact",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    firstName: "Former",
    lastName: "Contact",
    displayName: "Former Contact",
    primaryPhone: "+91 90000 05001",
    status: "archived",
    verificationStatus: "rejected",
    createdAt: "2026-03-01T09:00:00+05:30",
    updatedAt: "2026-07-01T09:00:00+05:30",
    archivedAt: "2026-07-01T09:00:00+05:30",
  },
  guardian("guardian-rajesh-joshi", "Rajesh", "Joshi", "Civil Engineer", "Joshi Associates", "rajesh.joshi@example.test", "+91 90000 07001", "Pimple Saudagar"),
  guardian("guardian-priyanka-bhosale", "Priyanka", "Bhosale", "Chartered Accountant", "Bhosale & Co.", "priyanka.bhosale@example.test", "+91 90000 08001", "Wakad"),
  guardian("guardian-amit-sawant", "Amit", "Sawant", "Bank Manager", "Maharashtra Cooperative Bank", "amit.sawant@example.test", "+91 90000 09001", "Baner"),
  guardian("guardian-neha-menon", "Neha", "Menon", "Software Engineer", "HinTech Systems", "neha.menon@example.test", "+91 90000 10001", "Hinjewadi"),
  guardian("guardian-suresh-chavan", "Suresh", "Chavan", "Pharmacist", "Chavan Medicals", "suresh.chavan@example.test", "+91 90000 11001", "Aundh"),
  guardian("guardian-kavita-pillai", "Kavita", "Pillai", "School Counselor", "Independent Practice", "kavita.pillai@example.test", "+91 90000 12001", "Rahatani"),
  guardian("guardian-imran-shaikh", "Imran", "Shaikh", "Logistics Supervisor", "Pune Freight Services", "imran.shaikh@example.test", "+91 90000 13001", "Thergaon"),
  guardian("guardian-pooja-rane", "Pooja", "Rane", "Homemaker", undefined, "pooja.rane@example.test", "+91 90000 14001", "Wakad"),
  ...grade8BAdditionalStudentSeeds.map((seed) =>
    guardian(
      seed.guardianId,
      seed.guardianFirstName,
      seed.guardianLastName,
      seed.guardianOccupation,
      seed.guardianEmployer,
      `${seed.guardianFirstName.toLowerCase()}.${seed.guardianLastName.toLowerCase()}@example.test`,
      seed.guardianPhone,
      seed.guardianAddress,
    ),
  ),
];

export const mockGuardianRelationships: GuardianStudentRelationship[] = [
  relationship("rel-stu-001-meera", "guardian-meera-kulkarni", "stu-001", "mother", true, false, true, true, true, true, true),
  relationship("rel-stu-001-sameer", "guardian-sameer-kulkarni", "stu-001", "father", false, false, true, true, true, true, true),
  relationship("rel-stu-002-nikhil", "guardian-nikhil-deshmukh", "stu-002", "father", true, false, true, true, true, true, true),
  relationship("rel-stu-006-nikhil", "guardian-nikhil-deshmukh", "stu-006", "relative", false, true, true, false, true, true, true),
  relationship("rel-stu-003-rohit", "guardian-rohit-nair", "stu-003", "legalGuardian", true, false, true, true, false, true, true),
  relationship("rel-stu-004-anita", "guardian-anita-sharma", "stu-004", "emergencyContact", false, true, true, false, false, true, true),
  relationship("rel-stu-007-rajesh", "guardian-rajesh-joshi", "stu-007", "father", true, false, true, true, true, true, true),
  relationship("rel-stu-008-priyanka", "guardian-priyanka-bhosale", "stu-008", "mother", true, false, true, true, true, true, true),
  relationship("rel-stu-009-amit", "guardian-amit-sawant", "stu-009", "father", true, false, true, true, true, true, true),
  relationship("rel-stu-010-neha", "guardian-neha-menon", "stu-010", "mother", true, false, true, true, true, true, true),
  relationship("rel-stu-011-suresh", "guardian-suresh-chavan", "stu-011", "father", true, false, true, true, true, true, true),
  relationship("rel-stu-012-kavita", "guardian-kavita-pillai", "stu-012", "mother", true, false, true, true, true, true, true),
  relationship("rel-stu-013-imran", "guardian-imran-shaikh", "stu-013", "father", true, false, true, true, true, true, true),
  relationship("rel-stu-014-pooja", "guardian-pooja-rane", "stu-014", "mother", true, false, true, true, true, true, true),
  ...grade8BAdditionalStudentSeeds.map((seed) =>
    relationship(
      `rel-${seed.studentId}-${seed.guardianId.replace("guardian-", "")}`,
      seed.guardianId,
      seed.studentId,
      seed.relationship,
      true,
      false,
      true,
      true,
      true,
      true,
      true,
    ),
  ),
];

function guardian(
  id: string,
  firstName: string,
  lastName: string,
  occupation: string,
  employer: string | undefined,
  email: string,
  primaryPhone: string,
  address: string,
): Guardian {
  return {
    id,
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    firstName,
    lastName,
    displayName: `${firstName} ${lastName}`,
    occupation,
    employer,
    email,
    primaryPhone,
    address,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    postalCode: "411057",
    preferredLanguage: "English",
    status: "active",
    verificationStatus: "verified",
    createdAt: "2026-04-03T09:00:00+05:30",
    updatedAt: "2026-08-12T10:00:00+05:30",
  };
}

function relationship(
  id: string,
  guardianId: string,
  studentId: string,
  relationshipType: GuardianStudentRelationship["relationshipType"],
  isPrimary: boolean,
  isEmergencyContact: boolean,
  canPickup: boolean,
  canReceiveAcademicCommunication: boolean,
  canReceiveFeeCommunication: boolean,
  canReceiveAttendanceCommunication: boolean,
  canReceiveGeneralCommunication: boolean,
): GuardianStudentRelationship {
  return {
    id,
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    guardianId,
    studentId,
    relationshipType,
    isPrimary,
    isEmergencyContact,
    canPickup,
    canReceiveAcademicCommunication,
    canReceiveFeeCommunication,
    canReceiveAttendanceCommunication,
    canReceiveGeneralCommunication,
    custodyStatus: "not_specified",
    startDate: "2026-04-01",
    createdAt: "2026-04-01T09:00:00+05:30",
    updatedAt: "2026-08-01T09:00:00+05:30",
  };
}
