import { tenantContext } from "@/lib/tenant-context";
import type { StudentAcademicPlacementReadModel } from "@/features/student-placements/types/student-placement";
import type { Student, StudentSummary } from "@/features/students/types/student";

export type MockStudentGuardian = {
  id: string;
  name: string;
};

export type Grade8BStudentSeed = {
  studentId: string;
  admissionNumber: string;
  studentCode: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender: Student["gender"];
  rollNumber: string;
  guardianId: string;
  guardianFirstName: string;
  guardianLastName: string;
  relationship: "father" | "mother";
  guardianOccupation: string;
  guardianEmployer?: string;
  guardianPhone: string;
  guardianAddress: string;
};

export const grade8BAdditionalStudentSeeds: Grade8BStudentSeed[] = [
  { studentId: "stu-015", admissionNumber: "SPS-2026-0501", studentCode: "STU-0501", firstName: "Aarohi", lastName: "Apte", dateOfBirth: "2013-02-11", gender: "female", rollNumber: "08B-10", guardianId: "guardian-vinay-apte", guardianFirstName: "Vinay", guardianLastName: "Apte", relationship: "father", guardianOccupation: "Project Manager", guardianEmployer: "Pune Infra Projects", guardianPhone: "+91 90000 15001", guardianAddress: "Wakad" },
  { studentId: "stu-016", admissionNumber: "SPS-2026-0502", studentCode: "STU-0502", firstName: "Vivaan", lastName: "Gokhale", dateOfBirth: "2012-09-24", gender: "male", rollNumber: "08B-11", guardianId: "guardian-rashmi-gokhale", guardianFirstName: "Rashmi", guardianLastName: "Gokhale", relationship: "mother", guardianOccupation: "Dentist", guardianEmployer: "Smile Care Clinic", guardianPhone: "+91 90000 15002", guardianAddress: "Pimple Saudagar" },
  { studentId: "stu-017", admissionNumber: "SPS-2026-0503", studentCode: "STU-0503", firstName: "Kiara", lastName: "More", dateOfBirth: "2013-06-17", gender: "female", rollNumber: "08B-12", guardianId: "guardian-sachin-more", guardianFirstName: "Sachin", guardianLastName: "More", relationship: "father", guardianOccupation: "Business Owner", guardianEmployer: "More Traders", guardianPhone: "+91 90000 15003", guardianAddress: "Thergaon" },
  { studentId: "stu-018", admissionNumber: "SPS-2026-0504", studentCode: "STU-0504", firstName: "Reyansh", lastName: "Datar", dateOfBirth: "2013-12-05", gender: "male", rollNumber: "08B-13", guardianId: "guardian-swati-datar", guardianFirstName: "Swati", guardianLastName: "Datar", relationship: "mother", guardianOccupation: "Lecturer", guardianEmployer: "Modern College", guardianPhone: "+91 90000 15004", guardianAddress: "Aundh" },
  { studentId: "stu-019", admissionNumber: "SPS-2026-0505", studentCode: "STU-0505", firstName: "Saanvi", lastName: "Bhise", dateOfBirth: "2013-04-02", gender: "female", rollNumber: "08B-14", guardianId: "guardian-mahesh-bhise", guardianFirstName: "Mahesh", guardianLastName: "Bhise", relationship: "father", guardianOccupation: "Chartered Accountant", guardianEmployer: "Bhise Associates", guardianPhone: "+91 90000 15005", guardianAddress: "Baner" },
  { studentId: "stu-020", admissionNumber: "SPS-2026-0506", studentCode: "STU-0506", firstName: "Atharva", lastName: "Kadam", dateOfBirth: "2012-11-29", gender: "male", rollNumber: "08B-15", guardianId: "guardian-pratibha-kadam", guardianFirstName: "Pratibha", guardianLastName: "Kadam", relationship: "mother", guardianOccupation: "HR Manager", guardianEmployer: "AutoCore India", guardianPhone: "+91 90000 15006", guardianAddress: "Hinjewadi" },
  { studentId: "stu-021", admissionNumber: "SPS-2026-0507", studentCode: "STU-0507", firstName: "Anvi", lastName: "Kulshreshtha", dateOfBirth: "2013-09-08", gender: "female", rollNumber: "08B-16", guardianId: "guardian-deepak-kulshreshtha", guardianFirstName: "Deepak", guardianLastName: "Kulshreshtha", relationship: "father", guardianOccupation: "Software Architect", guardianEmployer: "TechVista Labs", guardianPhone: "+91 90000 15007", guardianAddress: "Balewadi" },
  { studentId: "stu-022", admissionNumber: "SPS-2026-0508", studentCode: "STU-0508", firstName: "Dhruv", lastName: "Pawar", dateOfBirth: "2013-01-13", gender: "male", rollNumber: "08B-17", guardianId: "guardian-manjiri-pawar", guardianFirstName: "Manjiri", guardianLastName: "Pawar", relationship: "mother", guardianOccupation: "Physiotherapist", guardianEmployer: "Active Life Rehab", guardianPhone: "+91 90000 15008", guardianAddress: "Rahatani" },
  { studentId: "stu-023", admissionNumber: "SPS-2026-0509", studentCode: "STU-0509", firstName: "Myra", lastName: "Soman", dateOfBirth: "2012-08-19", gender: "female", rollNumber: "08B-18", guardianId: "guardian-kedar-soman", guardianFirstName: "Kedar", guardianLastName: "Soman", relationship: "father", guardianOccupation: "Operations Head", guardianEmployer: "Soman Logistics", guardianPhone: "+91 90000 15009", guardianAddress: "Wakad" },
  { studentId: "stu-024", admissionNumber: "SPS-2026-0510", studentCode: "STU-0510", firstName: "Arnav", lastName: "Bendre", dateOfBirth: "2013-05-30", gender: "male", rollNumber: "08B-19", guardianId: "guardian-ritu-bendre", guardianFirstName: "Ritu", guardianLastName: "Bendre", relationship: "mother", guardianOccupation: "Interior Designer", guardianEmployer: "Ritu Bendre Design", guardianPhone: "+91 90000 15010", guardianAddress: "Pimple Nilakh" },
  { studentId: "stu-025", admissionNumber: "SPS-2026-0511", studentCode: "STU-0511", firstName: "Mihika", lastName: "Naik", dateOfBirth: "2013-03-16", gender: "female", rollNumber: "08B-20", guardianId: "guardian-ganesh-naik", guardianFirstName: "Ganesh", guardianLastName: "Naik", relationship: "father", guardianOccupation: "Marketing Manager", guardianEmployer: "West Pune Retail", guardianPhone: "+91 90000 15011", guardianAddress: "Aundh" },
  { studentId: "stu-026", admissionNumber: "SPS-2026-0512", studentCode: "STU-0512", firstName: "Kabir", lastName: "Tambe", dateOfBirth: "2012-10-07", gender: "male", rollNumber: "08B-21", guardianId: "guardian-asmita-tambe", guardianFirstName: "Asmita", guardianLastName: "Tambe", relationship: "mother", guardianOccupation: "Bank Officer", guardianEmployer: "Union Bank", guardianPhone: "+91 90000 15012", guardianAddress: "Baner" },
  { studentId: "stu-027", admissionNumber: "SPS-2026-0513", studentCode: "STU-0513", firstName: "Prisha", lastName: "Lad", dateOfBirth: "2013-07-26", gender: "female", rollNumber: "08B-22", guardianId: "guardian-nitin-lad", guardianFirstName: "Nitin", guardianLastName: "Lad", relationship: "father", guardianOccupation: "Mechanical Engineer", guardianEmployer: "Pune Precision Works", guardianPhone: "+91 90000 15013", guardianAddress: "Chinchwad" },
  { studentId: "stu-028", admissionNumber: "SPS-2026-0514", studentCode: "STU-0514", firstName: "Shaurya", lastName: "Wagh", dateOfBirth: "2013-11-03", gender: "male", rollNumber: "08B-23", guardianId: "guardian-anjali-wagh", guardianFirstName: "Anjali", guardianLastName: "Wagh", relationship: "mother", guardianOccupation: "Nutritionist", guardianEmployer: "Family Wellness Clinic", guardianPhone: "+91 90000 15014", guardianAddress: "Ravet" },
  { studentId: "stu-029", admissionNumber: "SPS-2026-0515", studentCode: "STU-0515", firstName: "Navya", lastName: "Pandit", dateOfBirth: "2012-12-21", gender: "female", rollNumber: "08B-24", guardianId: "guardian-sandeep-pandit", guardianFirstName: "Sandeep", guardianLastName: "Pandit", relationship: "father", guardianOccupation: "Advocate", guardianEmployer: "District Court Pune", guardianPhone: "+91 90000 15015", guardianAddress: "Shivajinagar" },
  { studentId: "stu-030", admissionNumber: "SPS-2026-0516", studentCode: "STU-0516", firstName: "Ira", lastName: "Mhatre", dateOfBirth: "2013-08-06", gender: "female", rollNumber: "08B-25", guardianId: "guardian-reshma-mhatre", guardianFirstName: "Reshma", guardianLastName: "Mhatre", relationship: "mother", guardianOccupation: "Quality Analyst", guardianEmployer: "InfoBridge Services", guardianPhone: "+91 90000 15016", guardianAddress: "Hinjewadi" },
  { studentId: "stu-031", admissionNumber: "SPS-2026-0517", studentCode: "STU-0517", firstName: "Aditya", lastName: "Jadhav", dateOfBirth: "2013-02-28", gender: "male", rollNumber: "08B-26", guardianId: "guardian-shailesh-jadhav", guardianFirstName: "Shailesh", guardianLastName: "Jadhav", relationship: "father", guardianOccupation: "Police Inspector", guardianEmployer: "Maharashtra Police", guardianPhone: "+91 90000 15017", guardianAddress: "Pimple Gurav" },
  { studentId: "stu-032", admissionNumber: "SPS-2026-0518", studentCode: "STU-0518", firstName: "Diya", lastName: "Karnik", dateOfBirth: "2013-06-01", gender: "female", rollNumber: "08B-27", guardianId: "guardian-medha-karnik", guardianFirstName: "Medha", guardianLastName: "Karnik", relationship: "mother", guardianOccupation: "Teacher", guardianEmployer: "City Pride School", guardianPhone: "+91 90000 15018", guardianAddress: "Wakad" },
  { studentId: "stu-033", admissionNumber: "SPS-2026-0519", studentCode: "STU-0519", firstName: "Yash", lastName: "Gadgil", dateOfBirth: "2012-09-11", gender: "male", rollNumber: "08B-28", guardianId: "guardian-ravindra-gadgil", guardianFirstName: "Ravindra", guardianLastName: "Gadgil", relationship: "father", guardianOccupation: "Finance Controller", guardianEmployer: "Pune Auto Components", guardianPhone: "+91 90000 15019", guardianAddress: "Aundh" },
  { studentId: "stu-034", admissionNumber: "SPS-2026-0520", studentCode: "STU-0520", firstName: "Avni", lastName: "Barve", dateOfBirth: "2013-04-23", gender: "female", rollNumber: "08B-29", guardianId: "guardian-vaidehi-barve", guardianFirstName: "Vaidehi", guardianLastName: "Barve", relationship: "mother", guardianOccupation: "Graphic Designer", guardianEmployer: "Blue Dot Studio", guardianPhone: "+91 90000 15020", guardianAddress: "Baner" },
  { studentId: "stu-035", admissionNumber: "SPS-2026-0521", studentCode: "STU-0521", firstName: "Rudra", lastName: "Kale", dateOfBirth: "2013-01-07", gender: "male", rollNumber: "08B-30", guardianId: "guardian-prakash-kale", guardianFirstName: "Prakash", guardianLastName: "Kale", relationship: "father", guardianOccupation: "Civil Contractor", guardianEmployer: "Kale Constructions", guardianPhone: "+91 90000 15021", guardianAddress: "Rahatani" },
  { studentId: "stu-036", admissionNumber: "SPS-2026-0522", studentCode: "STU-0522", firstName: "Anika", lastName: "Kohli", dateOfBirth: "2012-11-15", gender: "female", rollNumber: "08B-31", guardianId: "guardian-sonal-kohli", guardianFirstName: "Sonal", guardianLastName: "Kohli", relationship: "mother", guardianOccupation: "Product Manager", guardianEmployer: "Nexora Tech", guardianPhone: "+91 90000 15022", guardianAddress: "Hinjewadi" },
  { studentId: "stu-037", admissionNumber: "SPS-2026-0523", studentCode: "STU-0523", firstName: "Samarth", lastName: "Bapat", dateOfBirth: "2013-07-04", gender: "male", rollNumber: "08B-32", guardianId: "guardian-omkar-bapat", guardianFirstName: "Omkar", guardianLastName: "Bapat", relationship: "father", guardianOccupation: "Consultant", guardianEmployer: "Bapat Advisory", guardianPhone: "+91 90000 15023", guardianAddress: "Balewadi" },
  { studentId: "stu-038", admissionNumber: "SPS-2026-0524", studentCode: "STU-0524", firstName: "Tara", lastName: "Lohia", dateOfBirth: "2013-12-19", gender: "female", rollNumber: "08B-33", guardianId: "guardian-namrata-lohia", guardianFirstName: "Namrata", guardianLastName: "Lohia", relationship: "mother", guardianOccupation: "Textile Entrepreneur", guardianEmployer: "Lohia Handlooms", guardianPhone: "+91 90000 15024", guardianAddress: "Pimple Saudagar" },
  { studentId: "stu-039", admissionNumber: "SPS-2026-0525", studentCode: "STU-0525", firstName: "Vihaan", lastName: "Sathe", dateOfBirth: "2012-08-31", gender: "male", rollNumber: "08B-34", guardianId: "guardian-ajay-sathe", guardianFirstName: "Ajay", guardianLastName: "Sathe", relationship: "father", guardianOccupation: "Architect", guardianEmployer: "Sathe Design Group", guardianPhone: "+91 90000 15025", guardianAddress: "Wakad" },
  { studentId: "stu-040", admissionNumber: "SPS-2026-0526", studentCode: "STU-0526", firstName: "Meera", lastName: "Rao", dateOfBirth: "2013-05-12", gender: "female", rollNumber: "08B-35", guardianId: "guardian-latha-rao", guardianFirstName: "Latha", guardianLastName: "Rao", relationship: "mother", guardianOccupation: "Clinical Researcher", guardianEmployer: "Pune Biolabs", guardianPhone: "+91 90000 15026", guardianAddress: "Aundh" },
  { studentId: "stu-041", admissionNumber: "SPS-2026-0527", studentCode: "STU-0527", firstName: "Krish", lastName: "Tiwari", dateOfBirth: "2013-10-26", gender: "male", rollNumber: "08B-36", guardianId: "guardian-mukesh-tiwari", guardianFirstName: "Mukesh", guardianLastName: "Tiwari", relationship: "father", guardianOccupation: "Sales Director", guardianEmployer: "Maitri Foods", guardianPhone: "+91 90000 15027", guardianAddress: "Thergaon" },
  { studentId: "stu-042", admissionNumber: "SPS-2026-0528", studentCode: "STU-0528", firstName: "Rhea", lastName: "Nadkarni", dateOfBirth: "2013-03-03", gender: "female", rollNumber: "08B-37", guardianId: "guardian-shruti-nadkarni", guardianFirstName: "Shruti", guardianLastName: "Nadkarni", relationship: "mother", guardianOccupation: "Auditor", guardianEmployer: "KPMG India", guardianPhone: "+91 90000 15028", guardianAddress: "Baner" },
  { studentId: "stu-043", admissionNumber: "SPS-2026-0529", studentCode: "STU-0529", firstName: "Harsh", lastName: "Mahajan", dateOfBirth: "2012-12-02", gender: "male", rollNumber: "08B-38", guardianId: "guardian-rohan-mahajan", guardianFirstName: "Rohan", guardianLastName: "Mahajan", relationship: "father", guardianOccupation: "Restaurant Owner", guardianEmployer: "Mahajan Foods", guardianPhone: "+91 90000 15029", guardianAddress: "Ravet" },
  { studentId: "stu-044", admissionNumber: "SPS-2026-0530", studentCode: "STU-0530", firstName: "Jiya", lastName: "Phadke", dateOfBirth: "2013-06-25", gender: "female", rollNumber: "08B-39", guardianId: "guardian-aparna-phadke", guardianFirstName: "Aparna", guardianLastName: "Phadke", relationship: "mother", guardianOccupation: "Classical Music Teacher", guardianEmployer: "Swarangan Academy", guardianPhone: "+91 90000 15030", guardianAddress: "Pimple Nilakh" },
  { studentId: "stu-045", admissionNumber: "SPS-2026-0531", studentCode: "STU-0531", firstName: "Neil", lastName: "Mathur", dateOfBirth: "2013-01-18", gender: "male", rollNumber: "08B-40", guardianId: "guardian-sanjay-mathur", guardianFirstName: "Sanjay", guardianLastName: "Mathur", relationship: "father", guardianOccupation: "Supply Chain Manager", guardianEmployer: "Western Logistics", guardianPhone: "+91 90000 15031", guardianAddress: "Hinjewadi" },
  { studentId: "stu-046", admissionNumber: "SPS-2026-0532", studentCode: "STU-0532", firstName: "Pari", lastName: "Dixit", dateOfBirth: "2012-09-05", gender: "female", rollNumber: "08B-41", guardianId: "guardian-kalpana-dixit", guardianFirstName: "Kalpana", guardianLastName: "Dixit", relationship: "mother", guardianOccupation: "Insurance Advisor", guardianEmployer: "LIC India", guardianPhone: "+91 90000 15032", guardianAddress: "Wakad" },
  { studentId: "stu-047", admissionNumber: "SPS-2026-0533", studentCode: "STU-0533", firstName: "Manan", lastName: "Bora", dateOfBirth: "2013-04-14", gender: "male", rollNumber: "08B-42", guardianId: "guardian-hitesh-bora", guardianFirstName: "Hitesh", guardianLastName: "Bora", relationship: "father", guardianOccupation: "Jewellery Retailer", guardianEmployer: "Bora Jewellers", guardianPhone: "+91 90000 15033", guardianAddress: "Chinchwad" },
  { studentId: "stu-048", admissionNumber: "SPS-2026-0534", studentCode: "STU-0534", firstName: "Siya", lastName: "Gandhi", dateOfBirth: "2013-11-22", gender: "female", rollNumber: "08B-43", guardianId: "guardian-mina-gandhi", guardianFirstName: "Mina", guardianLastName: "Gandhi", relationship: "mother", guardianOccupation: "Boutique Owner", guardianEmployer: "Mina Studio", guardianPhone: "+91 90000 15034", guardianAddress: "Baner" },
  { studentId: "stu-049", admissionNumber: "SPS-2026-0535", studentCode: "STU-0535", firstName: "Aryan", lastName: "Shetty", dateOfBirth: "2012-10-30", gender: "male", rollNumber: "08B-44", guardianId: "guardian-pradeep-shetty", guardianFirstName: "Pradeep", guardianLastName: "Shetty", relationship: "father", guardianOccupation: "Hotel Manager", guardianEmployer: "Westside Hotels", guardianPhone: "+91 90000 15035", guardianAddress: "Aundh" },
  { studentId: "stu-050", admissionNumber: "SPS-2026-0536", studentCode: "STU-0536", firstName: "Naira", lastName: "Agrawal", dateOfBirth: "2013-07-15", gender: "female", rollNumber: "08B-45", guardianId: "guardian-poonam-agrawal", guardianFirstName: "Poonam", guardianLastName: "Agrawal", relationship: "mother", guardianOccupation: "Tax Consultant", guardianEmployer: "Agrawal Tax Services", guardianPhone: "+91 90000 15036", guardianAddress: "Pimple Saudagar" },
  { studentId: "stu-051", admissionNumber: "SPS-2026-0537", studentCode: "STU-0537", firstName: "Laksh", lastName: "Khurana", dateOfBirth: "2013-02-07", gender: "male", rollNumber: "08B-46", guardianId: "guardian-vikas-khurana", guardianFirstName: "Vikas", guardianLastName: "Khurana", relationship: "father", guardianOccupation: "Procurement Lead", guardianEmployer: "AutoLine Systems", guardianPhone: "+91 90000 15037", guardianAddress: "Rahatani" },
  { studentId: "stu-052", admissionNumber: "SPS-2026-0538", studentCode: "STU-0538", firstName: "Aisha", lastName: "Ansari", dateOfBirth: "2012-08-12", gender: "female", rollNumber: "08B-47", guardianId: "guardian-salma-ansari", guardianFirstName: "Salma", guardianLastName: "Ansari", relationship: "mother", guardianOccupation: "Pharmacist", guardianEmployer: "Ansari Pharmacy", guardianPhone: "+91 90000 15038", guardianAddress: "Thergaon" },
  { studentId: "stu-053", admissionNumber: "SPS-2026-0539", studentCode: "STU-0539", firstName: "Dev", lastName: "Rastogi", dateOfBirth: "2013-05-04", gender: "male", rollNumber: "08B-48", guardianId: "guardian-ashish-rastogi", guardianFirstName: "Ashish", guardianLastName: "Rastogi", relationship: "father", guardianOccupation: "Data Analyst", guardianEmployer: "Insight Metrics", guardianPhone: "+91 90000 15039", guardianAddress: "Hinjewadi" },
  { studentId: "stu-054", admissionNumber: "SPS-2026-0540", studentCode: "STU-0540", firstName: "Kavya", lastName: "Desai", dateOfBirth: "2013-09-27", gender: "female", rollNumber: "08B-49", guardianId: "guardian-hema-desai", guardianFirstName: "Hema", guardianLastName: "Desai", relationship: "mother", guardianOccupation: "Civil Services Officer", guardianEmployer: "PMC", guardianPhone: "+91 90000 15040", guardianAddress: "Shivajinagar" },
  { studentId: "stu-055", admissionNumber: "SPS-2026-0541", studentCode: "STU-0541", firstName: "Parth", lastName: "Shinde", dateOfBirth: "2012-12-14", gender: "male", rollNumber: "08B-50", guardianId: "guardian-mangesh-shinde", guardianFirstName: "Mangesh", guardianLastName: "Shinde", relationship: "father", guardianOccupation: "Electrical Engineer", guardianEmployer: "MSEDCL", guardianPhone: "+91 90000 15041", guardianAddress: "Ravet" },
  { studentId: "stu-056", admissionNumber: "SPS-2026-0542", studentCode: "STU-0542", firstName: "Trisha", lastName: "Chitale", dateOfBirth: "2013-06-09", gender: "female", rollNumber: "08B-51", guardianId: "guardian-mrunal-chitale", guardianFirstName: "Mrunal", guardianLastName: "Chitale", relationship: "mother", guardianOccupation: "Research Scientist", guardianEmployer: "NCL Pune", guardianPhone: "+91 90000 15042", guardianAddress: "Pashan" },
  { studentId: "stu-057", admissionNumber: "SPS-2026-0543", studentCode: "STU-0543", firstName: "Raghav", lastName: "Patwardhan", dateOfBirth: "2013-03-20", gender: "male", rollNumber: "08B-52", guardianId: "guardian-milind-patwardhan", guardianFirstName: "Milind", guardianLastName: "Patwardhan", relationship: "father", guardianOccupation: "Corporate Trainer", guardianEmployer: "SkillEdge Learning", guardianPhone: "+91 90000 15043", guardianAddress: "Baner" },
  { studentId: "stu-058", admissionNumber: "SPS-2026-0544", studentCode: "STU-0544", firstName: "Mahika", lastName: "Bajaj", dateOfBirth: "2013-10-09", gender: "female", rollNumber: "08B-53", guardianId: "guardian-rupali-bajaj", guardianFirstName: "Rupali", guardianLastName: "Bajaj", relationship: "mother", guardianOccupation: "Event Planner", guardianEmployer: "Bajaj Events", guardianPhone: "+91 90000 15044", guardianAddress: "Wakad" },
  { studentId: "stu-059", admissionNumber: "SPS-2026-0545", studentCode: "STU-0545", firstName: "Omkar", lastName: "Reddy", dateOfBirth: "2012-11-01", gender: "male", rollNumber: "08B-54", guardianId: "guardian-srinivas-reddy", guardianFirstName: "Srinivas", guardianLastName: "Reddy", relationship: "father", guardianOccupation: "Cloud Engineer", guardianEmployer: "CloudMitra", guardianPhone: "+91 90000 15045", guardianAddress: "Hinjewadi" },
  { studentId: "stu-060", admissionNumber: "SPS-2026-0546", studentCode: "STU-0546", firstName: "Aaradhya", lastName: "Thakur", dateOfBirth: "2013-01-31", gender: "female", rollNumber: "08B-55", guardianId: "guardian-sunita-thakur", guardianFirstName: "Sunita", guardianLastName: "Thakur", relationship: "mother", guardianOccupation: "Nurse", guardianEmployer: "Ruby Hall Clinic", guardianPhone: "+91 90000 15046", guardianAddress: "Aundh" },
  { studentId: "stu-061", admissionNumber: "SPS-2026-0547", studentCode: "STU-0547", firstName: "Kian", lastName: "Kapadia", dateOfBirth: "2013-08-02", gender: "male", rollNumber: "08B-56", guardianId: "guardian-nilesh-kapadia", guardianFirstName: "Nilesh", guardianLastName: "Kapadia", relationship: "father", guardianOccupation: "Investment Advisor", guardianEmployer: "Kapadia Wealth", guardianPhone: "+91 90000 15047", guardianAddress: "Balewadi" },
  { studentId: "stu-062", admissionNumber: "SPS-2026-0548", studentCode: "STU-0548", firstName: "Vanya", lastName: "Saxena", dateOfBirth: "2013-04-27", gender: "female", rollNumber: "08B-57", guardianId: "guardian-ritu-saxena", guardianFirstName: "Ritu", guardianLastName: "Saxena", relationship: "mother", guardianOccupation: "UX Designer", guardianEmployer: "Studio Pixel", guardianPhone: "+91 90000 15048", guardianAddress: "Pimple Saudagar" },
  { studentId: "stu-063", admissionNumber: "SPS-2026-0549", studentCode: "STU-0549", firstName: "Tanmay", lastName: "Vaidya", dateOfBirth: "2012-09-18", gender: "male", rollNumber: "08B-58", guardianId: "guardian-ramesh-vaidya", guardianFirstName: "Ramesh", guardianLastName: "Vaidya", relationship: "father", guardianOccupation: "Ayurvedic Doctor", guardianEmployer: "Vaidya Clinic", guardianPhone: "+91 90000 15049", guardianAddress: "Rahatani" },
  { studentId: "stu-064", admissionNumber: "SPS-2026-0550", studentCode: "STU-0550", firstName: "Mira", lastName: "Sengupta", dateOfBirth: "2013-12-11", gender: "female", rollNumber: "08B-59", guardianId: "guardian-anindita-sengupta", guardianFirstName: "Anindita", guardianLastName: "Sengupta", relationship: "mother", guardianOccupation: "Publisher", guardianEmployer: "Sengupta Books", guardianPhone: "+91 90000 15050", guardianAddress: "Baner" },
];

const grade8BAdditionalStudentGuardians: MockStudentGuardian[] = grade8BAdditionalStudentSeeds.map((seed) => ({
  id: seed.guardianId,
  name: `${seed.guardianFirstName} ${seed.guardianLastName}`,
}));

export const grade8BAdditionalStudents: Student[] = grade8BAdditionalStudentSeeds.map((seed, index) => {
  const admissionDay = String(8 + Math.floor(index / 5)).padStart(2, "0");

  return {
    id: seed.studentId,
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: seed.admissionNumber,
    studentCode: seed.studentCode,
    firstName: seed.firstName,
    lastName: seed.lastName,
    displayName: `${seed.firstName} ${seed.lastName}`,
    dateOfBirth: seed.dateOfBirth,
    gender: seed.gender,
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: seed.rollNumber,
    },
    admissionDate: `2026-04-${admissionDay}`,
    guardians: [
      {
        guardianId: seed.guardianId,
        studentId: seed.studentId,
        relationship: seed.relationship,
        isPrimary: true,
      },
    ],
    createdAt: `2026-04-${admissionDay}T09:00:00+05:30`,
    updatedAt: "2026-08-13T09:00:00+05:30",
  };
});

export const mockStudentGuardians: MockStudentGuardian[] = [
  { id: "guardian-meera-kulkarni", name: "Meera Kulkarni" },
  { id: "guardian-nikhil-deshmukh", name: "Nikhil Deshmukh" },
  { id: "guardian-rohit-nair", name: "Rohit Nair" },
  { id: "guardian-sneha-patil", name: "Sneha Patil" },
  { id: "guardian-farah-khan", name: "Farah Khan" },
  { id: "guardian-vivek-iyer", name: "Vivek Iyer" },
  { id: "guardian-rajesh-joshi", name: "Rajesh Joshi" },
  { id: "guardian-priyanka-bhosale", name: "Priyanka Bhosale" },
  { id: "guardian-amit-sawant", name: "Amit Sawant" },
  { id: "guardian-neha-menon", name: "Neha Menon" },
  { id: "guardian-suresh-chavan", name: "Suresh Chavan" },
  { id: "guardian-kavita-pillai", name: "Kavita Pillai" },
  { id: "guardian-imran-shaikh", name: "Imran Shaikh" },
  { id: "guardian-pooja-rane", name: "Pooja Rane" },
  ...grade8BAdditionalStudentGuardians,
];

export const mockStudents: Student[] = [
  {
    id: "stu-001",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0148",
    studentCode: "STU-0148",
    firstName: "Ananya",
    lastName: "Kulkarni",
    displayName: "Ananya Kulkarni",
    dateOfBirth: "2013-04-18",
    gender: "female",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-a",
      sectionName: "A",
      rollNumber: "08A-04",
    },
    admissionDate: "2026-04-02",
    guardians: [
      {
        guardianId: "guardian-meera-kulkarni",
        studentId: "stu-001",
        relationship: "mother",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-02T09:30:00+05:30",
    updatedAt: "2026-08-08T11:20:00+05:30",
  },
  {
    id: "stu-002",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0193",
    studentCode: "STU-0193",
    firstName: "Aarav",
    lastName: "Deshmukh",
    displayName: "Aarav Deshmukh",
    dateOfBirth: "2011-11-09",
    gender: "male",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-10",
      className: "Grade 10",
      sectionId: "section-grade-10-b",
      sectionName: "B",
      rollNumber: "10B-11",
    },
    admissionDate: "2026-04-04",
    guardians: [
      {
        guardianId: "guardian-nikhil-deshmukh",
        studentId: "stu-002",
        relationship: "father",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-04T10:10:00+05:30",
    updatedAt: "2026-08-10T14:05:00+05:30",
  },
  {
    id: "stu-003",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0226",
    studentCode: "STU-0226",
    firstName: "Ishita",
    lastName: "Nair",
    displayName: "Ishita Nair",
    dateOfBirth: "2015-02-22",
    gender: "female",
    status: "pending",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-6",
      className: "Grade 6",
      sectionId: "section-grade-6-c",
      sectionName: "C",
      rollNumber: "06C-19",
    },
    admissionDate: "2026-04-08",
    guardians: [
      {
        guardianId: "guardian-rohit-nair",
        studentId: "stu-003",
        relationship: "guardian",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-08T12:45:00+05:30",
    updatedAt: "2026-08-11T09:50:00+05:30",
  },
  {
    id: "stu-004",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0281",
    studentCode: "STU-0281",
    firstName: "Kabir",
    lastName: "Patil",
    displayName: "Kabir Patil",
    dateOfBirth: "2018-08-15",
    gender: "male",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-3",
      className: "Grade 3",
      sectionId: "section-grade-3-a",
      sectionName: "A",
      rollNumber: "03A-07",
    },
    admissionDate: "2026-04-10",
    guardians: [
      {
        guardianId: "guardian-sneha-patil",
        studentId: "stu-004",
        relationship: "mother",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-10T11:15:00+05:30",
    updatedAt: "2026-08-09T16:30:00+05:30",
  },
  {
    id: "stu-005",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2025-0316",
    studentCode: "STU-0316",
    firstName: "Zoya",
    lastName: "Khan",
    displayName: "Zoya Khan",
    dateOfBirth: "2012-01-06",
    gender: "female",
    status: "transferred",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-9",
      className: "Grade 9",
      sectionId: "section-grade-9-a",
      sectionName: "A",
      rollNumber: "09A-21",
    },
    admissionDate: "2025-04-06",
    guardians: [
      {
        guardianId: "guardian-farah-khan",
        studentId: "stu-005",
        relationship: "mother",
        isPrimary: true,
      },
    ],
    createdAt: "2025-04-06T10:30:00+05:30",
    updatedAt: "2026-07-29T13:10:00+05:30",
  },
  {
    id: "stu-006",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0342",
    studentCode: "STU-0342",
    firstName: "Arjun",
    middleName: "R.",
    lastName: "Iyer",
    displayName: "Arjun R. Iyer",
    dateOfBirth: "2014-09-28",
    gender: "male",
    status: "inactive",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-7",
      className: "Grade 7",
      sectionId: "section-grade-7-b",
      sectionName: "B",
      rollNumber: "07B-16",
    },
    admissionDate: "2026-04-12",
    guardians: [
      {
        guardianId: "guardian-vivek-iyer",
        studentId: "stu-006",
        relationship: "father",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-12T09:05:00+05:30",
    updatedAt: "2026-08-06T15:40:00+05:30",
  },
  {
    id: "stu-007",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0417",
    studentCode: "STU-0417",
    firstName: "Riya",
    lastName: "Joshi",
    displayName: "Riya Joshi",
    dateOfBirth: "2013-07-12",
    gender: "female",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-01",
    },
    admissionDate: "2026-04-03",
    guardians: [
      {
        guardianId: "guardian-rajesh-joshi",
        studentId: "stu-007",
        relationship: "father",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-03T09:10:00+05:30",
    updatedAt: "2026-08-12T10:15:00+05:30",
  },
  {
    id: "stu-008",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0421",
    studentCode: "STU-0421",
    firstName: "Vedant",
    lastName: "Bhosale",
    displayName: "Vedant Bhosale",
    dateOfBirth: "2013-10-03",
    gender: "male",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-02",
    },
    admissionDate: "2026-04-03",
    guardians: [
      {
        guardianId: "guardian-priyanka-bhosale",
        studentId: "stu-008",
        relationship: "mother",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-03T09:25:00+05:30",
    updatedAt: "2026-08-12T10:20:00+05:30",
  },
  {
    id: "stu-009",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0428",
    studentCode: "STU-0428",
    firstName: "Aditi",
    lastName: "Sawant",
    displayName: "Aditi Sawant",
    dateOfBirth: "2013-01-29",
    gender: "female",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-03",
    },
    admissionDate: "2026-04-04",
    guardians: [
      {
        guardianId: "guardian-amit-sawant",
        studentId: "stu-009",
        relationship: "father",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-04T10:05:00+05:30",
    updatedAt: "2026-08-12T10:25:00+05:30",
  },
  {
    id: "stu-010",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0435",
    studentCode: "STU-0435",
    firstName: "Nikhil",
    lastName: "Menon",
    displayName: "Nikhil Menon",
    dateOfBirth: "2012-12-18",
    gender: "male",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-05",
    },
    admissionDate: "2026-04-05",
    guardians: [
      {
        guardianId: "guardian-neha-menon",
        studentId: "stu-010",
        relationship: "mother",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-05T09:35:00+05:30",
    updatedAt: "2026-08-12T10:30:00+05:30",
  },
  {
    id: "stu-011",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0442",
    studentCode: "STU-0442",
    firstName: "Tanvi",
    lastName: "Chavan",
    displayName: "Tanvi Chavan",
    dateOfBirth: "2013-05-21",
    gender: "female",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-06",
    },
    admissionDate: "2026-04-05",
    guardians: [
      {
        guardianId: "guardian-suresh-chavan",
        studentId: "stu-011",
        relationship: "father",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-05T09:50:00+05:30",
    updatedAt: "2026-08-12T10:35:00+05:30",
  },
  {
    id: "stu-012",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0451",
    studentCode: "STU-0451",
    firstName: "Ishan",
    lastName: "Pillai",
    displayName: "Ishan Pillai",
    dateOfBirth: "2013-03-09",
    gender: "male",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-07",
    },
    admissionDate: "2026-04-06",
    guardians: [
      {
        guardianId: "guardian-kavita-pillai",
        studentId: "stu-012",
        relationship: "mother",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-06T10:20:00+05:30",
    updatedAt: "2026-08-12T10:40:00+05:30",
  },
  {
    id: "stu-013",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0464",
    studentCode: "STU-0464",
    firstName: "Sara",
    lastName: "Shaikh",
    displayName: "Sara Shaikh",
    dateOfBirth: "2013-08-27",
    gender: "female",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-08",
    },
    admissionDate: "2026-04-07",
    guardians: [
      {
        guardianId: "guardian-imran-shaikh",
        studentId: "stu-013",
        relationship: "father",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-07T11:05:00+05:30",
    updatedAt: "2026-08-12T10:45:00+05:30",
  },
  {
    id: "stu-014",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    admissionNumber: "SPS-2026-0472",
    studentCode: "STU-0472",
    firstName: "Om",
    lastName: "Rane",
    displayName: "Om Rane",
    dateOfBirth: "2013-11-14",
    gender: "male",
    status: "active",
    academic: {
      academicYearId: tenantContext.academicYearId,
      classId: "class-grade-8",
      className: "Grade 8",
      sectionId: "section-grade-8-b-empty",
      sectionName: "B",
      rollNumber: "08B-09",
    },
    admissionDate: "2026-04-07",
    guardians: [
      {
        guardianId: "guardian-pooja-rane",
        studentId: "stu-014",
        relationship: "mother",
        isPrimary: true,
      },
    ],
    createdAt: "2026-04-07T11:20:00+05:30",
    updatedAt: "2026-08-12T10:50:00+05:30",
  },
  ...grade8BAdditionalStudents,
];

export function toStudentSummary(student: Student, activePlacement?: StudentAcademicPlacementReadModel): StudentSummary {
  const primaryGuardian = student.guardians.find((guardian) => guardian.isPrimary) ?? student.guardians[0];
  const guardian = primaryGuardian
    ? mockStudentGuardians.find((item) => item.id === primaryGuardian.guardianId)
    : undefined;

  return {
    id: student.id,
    tenantId: student.tenantId,
    schoolId: student.schoolId,
    campusId: student.campusId,
    academicYearId: student.academicYearId,
    admissionNumber: student.admissionNumber,
    studentCode: student.studentCode,
    displayName: student.displayName,
    avatarUrl: student.avatarUrl,
    gender: student.gender,
    status: student.status,
    admissionDate: student.admissionDate,
    classId: activePlacement?.classId ?? student.academic.classId,
    className: activePlacement?.className ?? student.academic.className ?? student.academic.classId,
    sectionId: activePlacement?.sectionId ?? student.academic.sectionId,
    sectionName: activePlacement?.sectionName ?? student.academic.sectionName ?? student.academic.sectionId,
    rollNumber: student.academic.rollNumber,
    primaryGuardian: primaryGuardian && guardian
      ? {
          guardianId: guardian.id,
          name: guardian.name,
          relationship: primaryGuardian.relationship,
        }
      : undefined,
  };
}
