import { tenantContext } from "@/lib/tenant-context";
import type {
  StudentDocument,
  StudentDocumentCategory,
  StudentDocumentRequirement,
  StudentDocumentType,
} from "@/features/students/types/student";

export const studentDocumentTypeLabels: Record<StudentDocumentType, string> = {
  identity_proof: "Identity Proof",
  government_id: "Government ID",
  birth_certificate: "Birth Certificate",
  previous_school_certificate: "Previous School Certificate",
  transfer_certificate: "Transfer Certificate",
  admission_form: "Admission Form",
  previous_academic_record: "Previous Academic Record",
  mark_sheet: "Mark Sheet",
  report_card: "Report Card",
  leaving_certificate: "Leaving Certificate",
  medical_certificate: "Medical Certificate",
  medical_record: "Medical Record",
  guardian_identity_document: "Guardian Identity Document",
  other: "Other",
};

export const studentDocumentCategoryLabels: Record<StudentDocumentCategory, string> = {
  identity: "Identity",
  admission: "Admission",
  academic: "Academic",
  medical: "Medical",
  guardian: "Guardian",
  other: "Other",
};

export const studentDocumentRequirements: StudentDocumentRequirement[] = [
  {
    documentType: "birth_certificate",
    category: "admission",
    title: "Birth Certificate",
    description: "Required for admission identity and age verification.",
    isRequired: true,
  },
  {
    documentType: "identity_proof",
    category: "identity",
    title: "Identity Proof",
    description: "Required identity document metadata; do not store raw identifier values in this stage.",
    isRequired: true,
  },
  {
    documentType: "previous_school_certificate",
    category: "admission",
    title: "Previous School Certificate",
    description: "Required for students joining from another school.",
    isRequired: true,
  },
  {
    documentType: "transfer_certificate",
    category: "admission",
    title: "Transfer Certificate",
    description: "Conditional document for transferred students.",
    isRequired: false,
  },
  {
    documentType: "medical_certificate",
    category: "medical",
    title: "Medical Certificate",
    description: "Optional medical document; expiry can be tracked when applicable.",
    isRequired: false,
    allowExpiry: true,
  },
  {
    documentType: "guardian_identity_document",
    category: "guardian",
    title: "Guardian Identity Document",
    description: "Optional guardian identity reference.",
    isRequired: false,
  },
];

export const mockStudentDocuments: StudentDocument[] = [
  {
    id: "doc-stu-001-birth",
    studentId: "stu-001",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    documentType: "birth_certificate",
    category: "admission",
    title: "Birth Certificate",
    description: "Verified admission identity record.",
    attachment: {
      attachmentId: "att-stu-001-birth",
      fileName: "birth-certificate-ananya.pdf",
      mimeType: "application/pdf",
      fileSize: 248000,
      kind: "pdf",
      reference: "mock://att-stu-001-birth",
      storageKey: `tenants/${tenantContext.tenantId}/students/stu-001/documents/att-stu-001-birth`,
    },
    status: "active",
    verificationStatus: "verified",
    uploadedAt: "2026-04-02T10:15:00+05:30",
    uploadedBy: "school-office",
    verifiedAt: "2026-04-03T11:30:00+05:30",
    verifiedBy: "admission-office",
    isRequired: true,
    createdAt: "2026-04-02T10:15:00+05:30",
    updatedAt: "2026-04-03T11:30:00+05:30",
  },
  {
    id: "doc-stu-001-identity",
    studentId: "stu-001",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    documentType: "identity_proof",
    category: "identity",
    title: "Identity Proof",
    description: "Masked identity proof metadata only.",
    attachment: {
      attachmentId: "att-stu-001-identity",
      fileName: "identity-proof-masked.png",
      mimeType: "image/png",
      fileSize: 512000,
      kind: "image",
      reference: "mock://att-stu-001-identity",
      storageKey: `tenants/${tenantContext.tenantId}/students/stu-001/documents/att-stu-001-identity`,
    },
    status: "active",
    verificationStatus: "pending",
    uploadedAt: "2026-04-05T09:20:00+05:30",
    uploadedBy: "school-office",
    isRequired: true,
    createdAt: "2026-04-05T09:20:00+05:30",
    updatedAt: "2026-04-05T09:20:00+05:30",
  },
  {
    id: "doc-stu-002-medical",
    studentId: "stu-002",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    documentType: "medical_certificate",
    category: "medical",
    title: "Medical Certificate",
    attachment: {
      attachmentId: "att-stu-002-medical",
      fileName: "medical-certificate-aarav.pdf",
      mimeType: "application/pdf",
      fileSize: 312000,
      kind: "pdf",
      reference: "mock://att-stu-002-medical",
      storageKey: `tenants/${tenantContext.tenantId}/students/stu-002/documents/att-stu-002-medical`,
    },
    status: "active",
    verificationStatus: "expired",
    uploadedAt: "2026-04-05T15:10:00+05:30",
    uploadedBy: "school-office",
    expiresAt: "2026-07-31",
    isRequired: false,
    createdAt: "2026-04-05T15:10:00+05:30",
    updatedAt: "2026-08-01T08:00:00+05:30",
  },
  {
    id: "doc-stu-003-previous-school",
    studentId: "stu-003",
    tenantId: tenantContext.tenantId,
    schoolId: tenantContext.schoolId,
    campusId: tenantContext.campusId,
    academicYearId: tenantContext.academicYearId,
    documentType: "previous_school_certificate",
    category: "admission",
    title: "Previous School Certificate",
    rejectionReason: "Document scan is unreadable.",
    attachment: {
      attachmentId: "att-stu-003-previous-school",
      fileName: "previous-school-certificate-ishita.pdf",
      mimeType: "application/pdf",
      fileSize: 184000,
      kind: "pdf",
      reference: "mock://att-stu-003-previous-school",
      storageKey: `tenants/${tenantContext.tenantId}/students/stu-003/documents/att-stu-003-previous-school`,
    },
    status: "active",
    verificationStatus: "rejected",
    uploadedAt: "2026-04-08T13:30:00+05:30",
    uploadedBy: "school-office",
    isRequired: true,
    createdAt: "2026-04-08T13:30:00+05:30",
    updatedAt: "2026-04-09T10:25:00+05:30",
  },
];
