import type { NavSection, Permission, Role } from "@/types/erp";

export const rolePermissions: Record<Role, Permission[]> = {
  principal: [
    "dashboard.view",
    "student.view",
    "student.create",
    "student.update",
    "student.archive",
    "student.manage",
    "admission.view",
    "admission.create",
    "admission.edit",
    "admission.submit",
    "admission.review",
    "admission.verify_documents",
    "admission.schedule",
    "admission.shortlist",
    "admission.approve",
    "admission.reject",
    "admission.waitlist",
    "admission.confirm",
    "admission.enroll",
    "admission.export",
    "admission.manage_cycle",
    "admission.manage_capacity",
    "guardian.view",
    "guardian.create",
    "guardian.update",
    "guardian.archive",
    "guardian.link",
    "guardian.manage",
    "academic.view",
    "academic.manage",
    "timetable.view",
    "timetable.create",
    "timetable.update",
    "timetable.configure",
    "timetable.cell.configure",
    "timetable.validate",
    "timetable.publish",
    "timetable.manage",
    "attendance.view",
    "attendance.mark",
    "attendance.update",
    "attendance.correct",
    "attendance.history.view",
    "attendance.manage",
    "attendance.report",
    "attendance.integrity.view",
    "fees.view",
    "finance.view",
    "finance.record_payment",
    "finance.verify_payment",
    "finance.manage_refund",
    "finance.view_reports",
    "exam.publish",
    "hr.view",
    "hr.manage",
    "communication.view",
    "communication.send",
    "communication.broadcast",
    "communication.notice.create",
    "communication.manage",
  ],
  teacher: ["dashboard.view", "student.view", "academic.view", "timetable.view", "attendance.view", "attendance.history.view", "attendance.mark", "attendance.update", "communication.view", "communication.send"],
  accountant: [
    "dashboard.view",
    "student.view",
    "admission.view",
    "guardian.view",
    "attendance.view",
    "attendance.history.view",
    "attendance.report",
    "fees.view",
    "finance.view",
    "finance.record_payment",
    "finance.verify_payment",
    "finance.manage_refund",
    "finance.view_reports",
    "communication.view",
    "communication.send",
  ],
  hr: ["dashboard.view", "hr.view", "hr.manage", "attendance.view", "attendance.mark", "communication.view", "communication.send"],
  "system-admin": [
    "dashboard.view",
    "admin.manage",
    "student.view",
    "student.create",
    "student.update",
    "student.archive",
    "student.manage",
    "admission.view",
    "admission.create",
    "admission.edit",
    "admission.submit",
    "admission.review",
    "admission.verify_documents",
    "admission.schedule",
    "admission.shortlist",
    "admission.approve",
    "admission.reject",
    "admission.waitlist",
    "admission.confirm",
    "admission.enroll",
    "admission.export",
    "admission.manage_cycle",
    "admission.manage_capacity",
    "guardian.view",
    "guardian.create",
    "guardian.update",
    "guardian.archive",
    "guardian.link",
    "guardian.manage",
    "academic.view",
    "academic.manage",
    "timetable.view",
    "timetable.create",
    "timetable.update",
    "timetable.configure",
    "timetable.cell.configure",
    "timetable.validate",
    "timetable.publish",
    "timetable.manage",
    "attendance.view",
    "fees.view",
    "attendance.mark",
    "attendance.update",
    "attendance.correct",
    "attendance.history.view",
    "attendance.manage",
    "attendance.report",
    "attendance.integrity.view",
    "hr.view",
    "hr.manage",
    "finance.view",
    "finance.record_payment",
    "finance.verify_payment",
    "finance.manage_refund",
    "finance.view_reports",
    "communication.view",
    "communication.send",
    "communication.broadcast",
    "communication.notice.create",
    "communication.manage",
  ],
};

export const navigation: NavSection[] = [
  {
    label: "Overview",
    items: [
      {
        label: "Dashboard",
        href: "/#dashboard",
        permission: "dashboard.view",
        icon: "dashboard",
        activeMatch: ["/", "/dashboard"],
      },
    ],
  },
  {
    label: "People",
    items: [
      { label: "Students", href: "/students", permission: "student.view", icon: "students", activeMatch: ["/students", "#students"] },
      { label: "Guardian / Parents", href: "/guardians", permission: "guardian.view", icon: "parents", activeMatch: ["/guardians"] },
      {
        label: "Staff",
        href: "/staff",
        permission: "hr.view",
        icon: "users",
        activeMatch: ["/staff", "/hr/staff", "#staff"],
        children: [
          { label: "Directory", href: "/staff", permission: "hr.view", activeMatch: ["/staff"] },
          { label: "Departments", href: "/staff/departments", permission: "hr.view", activeMatch: ["/staff/departments"] },
          { label: "Designations", href: "/staff/designations", permission: "hr.view", activeMatch: ["/staff/designations"] },
          { label: "Staff Attendance", href: "/staff/attendance", permission: "hr.view", activeMatch: ["/staff/attendance"] },
          { label: "Staff Leave", href: "/staff/leave", permission: "hr.view", activeMatch: ["/staff/leave"] },
          { label: "Documents", href: "/staff/documents", permission: "hr.view", activeMatch: ["/staff/documents"] },
          { label: "Academic Assignments", href: "/staff/academic-assignments", permission: "hr.view", activeMatch: ["/staff/academic-assignments"] },
          { label: "Workload & Scheduling", href: "/staff/workload", permission: "hr.view", activeMatch: ["/staff/workload"] },
          { label: "Performance", href: "/staff/performance", permission: "hr.view", activeMatch: ["/staff/performance"] },
          { label: "HR Operations", href: "/staff/hr-operations", permission: "hr.view", activeMatch: ["/staff/hr-operations"] },
        ],
      },
    ],
  },
  {
    label: "Admissions",
    items: [
      {
        label: "Admissions",
        href: "/admissions",
        permission: "admission.view",
        icon: "admissions",
        badge: "Foundation",
        activeMatch: ["/admissions"],
        children: [
          { label: "Applications", href: "/admissions/applications", permission: "admission.view", activeMatch: ["/admissions/applications"] },
          { label: "New Application", href: "/admissions/applications/new", permission: "admission.create", activeMatch: ["/admissions/applications/new"] },
          { label: "Documents", href: "/admissions/documents", permission: "admission.view", activeMatch: ["/admissions/documents"] },
          { label: "Reviews", href: "/admissions/reviews", permission: "admission.review", activeMatch: ["/admissions/reviews"] },
          { label: "Evaluations", href: "/admissions/evaluations", permission: "admission.schedule", activeMatch: ["/admissions/evaluations"] },
          { label: "Seats", href: "/admissions/seats", permission: "admission.manage_capacity", activeMatch: ["/admissions/seats"] },
        ],
      },
    ],
  },
  {
    label: "Academics",
    items: [
      {
        label: "Academics",
        href: "/academics/classes",
        permission: "academic.view",
        icon: "academics",
        activeMatch: ["/academics", "#academics", "#timetable", "#homework", "#exams"],
        children: [
          { label: "Academic Years", href: "/academics/academic-years", permission: "academic.view", activeMatch: ["/academics/academic-years"] },
          { label: "Classes", href: "/academics/classes", permission: "academic.view", activeMatch: ["/academics/classes", "#academics"] },
          { label: "Sections", href: "/academics/sections", permission: "academic.view", activeMatch: ["/academics/sections"] },
          { label: "Student Placements", href: "/academics/student-placements", permission: "academic.view", activeMatch: ["/academics/student-placements"] },
          { label: "Promotions", href: "/academics/promotions", permission: "academic.view", activeMatch: ["/academics/promotions"] },
          { label: "Bulk Promotion Preview", href: "/academics/promotions/bulk-preview", permission: "academic.view", activeMatch: ["/academics/promotions/bulk-preview"] },
          { label: "Promotion Audit", href: "/academics/promotions/audit", permission: "academic.view", activeMatch: ["/academics/promotions/audit"] },
          { label: "Subjects", href: "/#academics", permission: "academic.view", activeMatch: ["/academics/subjects"] },
          {
            label: "Timetable",
            href: "/timetable",
            permission: "timetable.view",
            icon: "timetable",
            activeMatch: ["/timetable"],
            children: [
              { label: "Dashboard", href: "/timetable", permission: "timetable.view", activeMatch: ["/timetable"] },
              { label: "Maker", href: "/timetable/maker", permission: "timetable.update", activeMatch: ["/timetable/maker"] },
              { label: "Classes", href: "/timetable/classes", permission: "timetable.view", activeMatch: ["/timetable/classes"] },
              { label: "Teachers", href: "/timetable/teachers", permission: "timetable.view", activeMatch: ["/timetable/teachers"] },
              { label: "Rooms", href: "/timetable/rooms", permission: "timetable.view", activeMatch: ["/timetable/rooms"] },
              { label: "Templates", href: "/timetable/templates", permission: "timetable.view", activeMatch: ["/timetable/templates"] },
              { label: "Settings", href: "/timetable/settings", permission: "timetable.manage", activeMatch: ["/timetable/settings"] },
              { label: "Versions", href: "/timetable/versions", permission: "timetable.view", activeMatch: ["/timetable/versions"] },
            ],
          },
          { label: "Homework", href: "/#homework", permission: "attendance.mark", icon: "homework", activeMatch: ["/homework", "#homework"] },
          { label: "Assessments", href: "/#exams", permission: "exam.publish", icon: "assessments", activeMatch: ["/assessments", "#exams"] },
          { label: "Examinations", href: "/#exams", permission: "exam.publish", activeMatch: ["/examinations"] },
        ],
      },
    ],
  },
  {
    label: "Attendance",
    items: [
      {
        label: "Attendance",
        href: "/attendance",
        permission: "attendance.view",
        icon: "attendance",
        activeMatch: ["/attendance", "#attendance"],
        children: [
          { label: "Student Attendance", href: "/attendance", permission: "attendance.view", icon: "attendance", activeMatch: ["/attendance"] },
          { label: "Mark Attendance", href: "/attendance/mark", permission: "attendance.mark", icon: "attendance", activeMatch: ["/attendance/mark"] },
          { label: "Attendance History", href: "/attendance/history", permission: "attendance.history.view", icon: "attendance", activeMatch: ["/attendance/history"] },
          { label: "Attendance Reports", href: "/attendance/reports", permission: "attendance.report", icon: "reports", activeMatch: ["/attendance/reports"] },
          { label: "Attendance Export", href: "/attendance/export", permission: "attendance.report", icon: "reports", activeMatch: ["/attendance/export"] },
          {
            label: "Integrity",
            href: "/attendance/integrity",
            permission: "attendance.integrity.view",
            icon: "audit",
            activeMatch: ["/attendance/integrity"],
            children: [
              { label: "Snapshot Integrity", href: "/attendance/integrity", permission: "attendance.integrity.view", icon: "audit", activeMatch: ["/attendance/integrity"] },
              { label: "Repair Audit", href: "/attendance/integrity/audit", permission: "attendance.integrity.view", icon: "audit", activeMatch: ["/attendance/integrity/audit"] },
              { label: "Repair Queue", href: "/attendance/integrity/repairs", permission: "attendance.manage", icon: "audit", activeMatch: ["/attendance/integrity/repairs"] },
              { label: "Bulk Repair", href: "/attendance/integrity/bulk-repair", permission: "attendance.manage", icon: "audit", activeMatch: ["/attendance/integrity/bulk-repair"] },
            ],
          },
          { label: "Staff Attendance", href: "/staff/attendance", permission: "hr.view", icon: "attendance", activeMatch: ["/staff/attendance"] },
        ],
      },
    ],
  },
  {
    label: "Finance",
    items: [
      {
        label: "Finance",
        href: "/finance",
        permission: "fees.view",
        icon: "finance",
        activeMatch: ["/finance", "#payments"],
        children: [
          { label: "Dashboard", href: "/finance", permission: "fees.view", activeMatch: ["/finance"] },
          { label: "Invoices", href: "/finance/invoices", permission: "fees.view", activeMatch: ["/finance/invoices"] },
          { label: "Payments", href: "/finance/payments", permission: "fees.view", activeMatch: ["/finance/payments", "#payments"] },
          { label: "Receipts", href: "/finance/receipts", permission: "fees.view", activeMatch: ["/finance/receipts"] },
          { label: "Dues", href: "/finance/dues", permission: "fees.view", activeMatch: ["/finance/dues"] },
          { label: "Refunds", href: "/finance/refunds", permission: "fees.view", activeMatch: ["/finance/refunds"] },
          { label: "Reports", href: "/finance/reports", permission: "fees.view", activeMatch: ["/finance/reports"] },
          { label: "Payroll", href: "/#payroll", permission: "hr.view", icon: "payroll", activeMatch: ["/hr/payroll", "#payroll"] },
        ],
      },
    ],
  },
  {
    label: "Communication",
    items: [
      {
        label: "Communication",
        href: "/communication",
        permission: "communication.view",
        icon: "communication",
        activeMatch: ["/communication"],
      },
    ],
  },
  {
    label: "Insights",
    items: [
      { label: "Reports", href: "/#reports", permission: "dashboard.view", icon: "reports", activeMatch: ["/reports", "#reports"] },
      { label: "Analytics", href: "/#reports", permission: "dashboard.view", icon: "reports", activeMatch: ["/analytics"] },
    ],
  },
  {
    label: "Administration",
    items: [
      { label: "Users", href: "/#admin", permission: "admin.manage", icon: "users", activeMatch: ["/admin/users", "#admin"] },
      { label: "Roles & Permissions", href: "/#admin", permission: "admin.manage", icon: "settings", activeMatch: ["/admin/roles", "/permissions"] },
      { label: "Audit Logs", href: "/#audit", permission: "admin.manage", icon: "audit", activeMatch: ["/audit", "#audit"] },
      { label: "Settings", href: "/#admin", permission: "admin.manage", icon: "settings", activeMatch: ["/settings"] },
    ],
  },
];
